# Generated by Django 5.0.6 on 2024-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=300)),
                ('Massage', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ContactInfos',
            },
        ),
    ]
